import { Metadata } from "next";

const url = process.env.NODE_ENV === "development" ? "http://localhost:3000" : "https://usehubrank.com";

type CustomMetadata = { name?: string; short_description?: string; url?: string; locale?: string; og_url?: string; author?: string };

export const siteConfig: Metadata & CustomMetadata = {
  name: "Hubrank",
  short_description: "Generate SEO blogs, social media captions & replies in just a few clicks.",
  description: "Supercharge your marketing with AI-generated content. Create SEO blogs and social media posts instantly. Grow your brand 10x faster with no effort.",
  url,
  locale: "en_US",
  keywords: [
    "seo ai",
    "seo ai writer",
    "seo blog writing",
    "ai for seo",
    "seo ai tools",
    "ai seo tools",
    "ai seo optimization",
    "seo writing",
    "seo blog",
    "ai seo content generator",
    "ai seo writer",
    "seo content writer",
    "best ai blog writer",
    "seo ai generator",
    "ai writer",
    "ai blog content generator",
    "best ai writer",
    "ai blog post generator",
    "ai seo content writing",
    "ai article generator",
    "seo ai free",
    "free ai seo tools",
    "seo text generator",
    "ai tools for seo",
    "article generator ai",
    "blog post writer",
    "ai content writer",
    "best ai for seo",
    "blog title generator",
    "ai content generator",
    "seo title generator",
    "ai tools for content writing",
    "seo tools",
    "content writer ai",
    "seo writing tools",
    "seo article writing",
    "best seo",
    "content generator ai",
    "best seo tools",
    "website seo",
    "content ai",
    "ai seo software",
    "best ai blog writing tool",
    "seo writing assistant",
    "blog writing tools",
    "content generator",
    "seo optimization ai",
    "ai content creator",
    "free ai blog content generator",
    "free seo"
  ],
  og_url: `${url}/marketing/og-image.webp`,
  author: "@usehubrank"
}
